name: penet_new
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision
  - cudatoolkit=11.3
  - pip
  - pip:
    - numpy
    - scipy
    - pandas
    - scikit-learn
    - scikit-image
    - simpleitk
    - pydicom
    - h5py
    - pillow
    - opencv-python
    - pywavelets
    - optuna
    - matplotlib
    - tqdm
    - imageio
    - requests
    - seaborn
    - jupyter
    - notebook
    - ipykernel
    - ipython
    - tensorboardx
    - lime
    - moviepy
    - shap