name: penet_new
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.11.1
  - cudatoolkit=11.3
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - h5py
  - pillow
  - opencv
  - matplotlib
  - tqdm
  - imageio
  - requests
  - seaborn
  - jupyter
  - notebook
  - ipykernel
  - ipython
  - pip:
      - simpleitk
      - pydicom
      - pywavelets
      - optuna
      - tensorboardx
      - lime
      - moviepy
      - shap