name: ctpe
channels:
  - conda-forge
  - defaults
  - pytorch
  - simpleitk

dependencies:
  # --- Core Frameworks ---
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.11.1
  - cudatoolkit=11.3
  - pip

  # --- Scientific & Data Handling ---
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - scikit-image
  - simpleitk
  - pydicom
  - h5py
  - pillow
  - opencv
  - pywavelets

  # --- Plotting & Utilities ---
  - matplotlib
  - tqdm
  - imageio
  - requests
  - seaborn

  # --- Jupyter & IPython ---
  - jupyter
  - notebook
  - ipykernel
  - ipython

  # --- Pip-specific packages ---
  - pip:
    - tensorboardx
    - lime
    - moviepy
    - shap
